### ISSUE TITLE
`realtime` NPM package

### ISSUE THREAD

**Issue by rvanasa** [coverslide/redis-ui#5]
Hi Richard,

I am currently working on a websocket proxy for Node.js and am hoping to use the package name `realtime` if possible. Would you be willing to transfer ownership of the current placeholder package to my account ([rvanasa](https://www.npmjs.com/~rvanasa)) on NPM? It would be tremendously appreciated.

Best regards,

~ Ryan

**Comment by coverslide** [comment]
Ok I've added you. Sorry it took so long.

**Comment by rvanasa** [comment]
Awesome; thank you!
